"""empty message

Revision ID: 47145946bc06
Revises: 
Create Date: 2021-07-07 21:03:37.052494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47145946bc06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=12), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('cpf', sa.Integer(), nullable=True),
    sa.Column('crm', sa.Integer(), nullable=True),
    sa.Column('especialidade', sa.String(length=20), nullable=True),
    sa.Column('localidade', sa.String(length=9), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=12), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remedio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=True),
    sa.Column('serve_para', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('potencia', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('horario', sa.Time(timezone=True), nullable=True),
    sa.Column('razao', sa.String(length=100), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('comentarios', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('exam_type', sa.String(length=30), nullable=False),
    sa.Column('resultado', sa.String(length=300), nullable=True),
    sa.Column('medico', sa.Integer(), nullable=False),
    sa.Column('paciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consulta'], ['consulta.id'], ),
    sa.ForeignKeyConstraint(['medico'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['paciente'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('medico', sa.Integer(), nullable=True),
    sa.Column('paciente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consulta'], ['consulta.id'], ),
    sa.ForeignKeyConstraint(['medico'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['paciente'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remedios_receitas',
    sa.Column('receita_id', sa.Integer(), nullable=True),
    sa.Column('remedio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ),
    sa.ForeignKeyConstraint(['remedio_id'], ['remedio.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remedios_receitas')
    op.drop_table('receita')
    op.drop_table('exame')
    op.drop_table('consulta')
    op.drop_table('remedio')
    op.drop_table('paciente')
    op.drop_table('medico')
    # ### end Alembic commands ###
